Move `/bank` page to v3
hackclub/v3 pull request #167
Opened 2021-08-11 03:12 UTC by eilla1

This PR moves the `/bank` page from v2 to v3 (Next.js + theme-ui). Sorry for taking forever on this PR 😅 

to-do before it's ready to review:
- [ ] Landing Section
- [ ] Features Section
- [ ] Events Section (`Testimonials.js`)
- [ ] "Everything you'll need" Section
- [ ] Sign Up section (`Start.js`)

2021-08-16 15:56 UTC, sampoder requested changes
Hey Ella! Thanks for the wonderful work on this PR, a few styles notes from me at the moment:


![image](https://user-images.githubusercontent.com/39828164/129592558-6af0cdb5-c368-4b6c-baa8-f397a2c050c7.jpeg)


![image](https://user-images.githubusercontent.com/39828164/129592641-ab6fc2d4-24f3-4279-9581-aed4db5ef1be.jpeg)

![image](https://user-images.githubusercontent.com/39828164/129592606-22d9c844-bf39-4135-bc0f-021188753107.jpeg)

![image](https://user-images.githubusercontent.com/39828164/129592702-6bbfcfc6-899d-4646-aaac-0b6fb9c5c41e.jpeg)

![image](https://user-images.githubusercontent.com/39828164/129592717-3b6c81b2-0acd-4e62-bfd3-f8f3837f6965.jpeg)
![image](https://user-images.githubusercontent.com/39828164/129592771-9a90b094-393e-4100-bf13-00977b4cb1f2.jpeg)

![image](https://user-images.githubusercontent.com/39828164/129592783-5d9f0a2b-b35a-4d8b-85fc-fe764b02f18a.jpeg)


![image](https://user-images.githubusercontent.com/39828164/129592523-f0848685-30c2-4c9c-828b-fd1fb24a5a73.jpeg)

2021-08-16 15:57 UTC, sampoder commented
Apologies for the poor handwringing, it may not leak through in my annotations as they are negative lol but thank you so so much for doing this, i really appreciate it and this is an incredible job you've down. Hats off to you

2021-08-16 15:58 UTC, sampoder commented
And the poor spelling.... everywhere

2021-08-16 17:53 UTC, eilla1 commented
Thanks for the review Sam! Really appreciate the detailed feedback!

i just have one more thing to fix hehe

2021-08-16 18:40 UTC, eilla1 commented
<img width="1392" alt="Screen Shot 2021-08-16 at 9 37 31 AM" src="https://user-images.githubusercontent.com/72365100/129613443-af85d06b-bacc-4d4d-902e-c4ff8360fc99.png">

The timeline looks like this for me 🤔

2021-08-17 02:41 UTC, sampoder commented on components/bank/Timeline.js
> +          'radial-gradient(ellipse farthest-corner at top left, #ff8c37, #ec3750',
```suggestion
          'radial-gradient(ellipse farthest-corner at top left, #ff8c37, #ec3750)',
```

2021-08-17 02:41 UTC, sampoder commented on components/bank/Timeline.js
> +          'radial-gradient(ellipse farthest-corner at top left, #ff8c37, #ec3750',
This should fix the timeline CSS

2021-08-17 14:30 UTC, sampoder requested changes
A few more notes on styles, thanks as always Ella

![IMG_0943](https://user-images.githubusercontent.com/39828164/129744718-d4b76775-cf7f-4aae-bded-960b0a102090.jpg)
![IMG_0942](https://user-images.githubusercontent.com/39828164/129744731-5d9db697-1dc3-4065-a7a0-b23a3c6e34a1.jpg)
![IMG_0941](https://user-images.githubusercontent.com/39828164/129744737-96f57b76-1075-4ad9-9e8f-6bea73db12d3.jpg)
![IMG_0940](https://user-images.githubusercontent.com/39828164/129744742-98a51b59-51ca-4c55-bdcb-aac2ad274f28.jpg)
![IMG_0939](https://user-images.githubusercontent.com/39828164/129744751-5228ff10-ef63-49bd-955e-8069c6fd15c4.jpg)
![IMG_0938](https://user-images.githubusercontent.com/39828164/129744774-7e1aa420-5618-4081-8773-e187a7334a92.jpg)

2021-08-20 03:54 UTC, sampoder requested changes
Could we balance out the vertical padding between the paragraph and the heading and the image, so they're all equal:

<img width="322" alt="Screenshot 2021-08-20 at 11 49 26 AM" src="https://user-images.githubusercontent.com/39828164/130176278-f17620d1-6dc8-45be-9f17-e129ccc9b32d.png">

Could we fix the events on mobile:

<img width="359" alt="Screenshot 2021-08-20 at 11 50 27 AM" src="https://user-images.githubusercontent.com/39828164/130176353-96bb9623-9c93-496e-a642-ca3a6f76c6ab.png">

The seven is also broken on mobile:

<img width="228" alt="Screenshot 2021-08-20 at 11 51 00 AM" src="https://user-images.githubusercontent.com/39828164/130176400-a6afb3f0-9e24-4e7f-8801-b8b5de0344d4.png">

Reduce the vertical padding here on mobile:

<img width="279" alt="Screenshot 2021-08-20 at 11 51 20 AM" src="https://user-images.githubusercontent.com/39828164/130176432-a4ede90f-1d8d-40f9-b85e-90798ccfbc89.png">

Have the timeline centered on mobile and the lines end at the circles and not go through 

<img width="444" alt="Screenshot 2021-08-20 at 11 52 01 AM" src="https://user-images.githubusercontent.com/39828164/130176481-2d4d3d53-75cb-490f-a0be-30fc97b0b497.png">

This text looks weird on mobile:

<img width="533" alt="Screenshot 2021-08-20 at 11 53 08 AM" src="https://user-images.githubusercontent.com/39828164/130176559-1443b92c-7edc-4043-ad50-98b74916b14c.png">

Thanks Ella!

2021-08-21 10:01 UTC, sampoder requested changes
This is really starting come together! The finish light is in sight, thank you so so much Ella!

Couple of notes, almost solely on mobile formatting (hooray! /s),

the Hack Club flag covers our header on the smallest of screens, could we add some more vertical padding to ensure this is avoided? 

<img width="782" alt="Screenshot 2021-08-21 at 5 37 28 PM" src="https://user-images.githubusercontent.com/39828164/130318140-8baafbec-89a9-47ce-bfbd-89bd54d63dc7.png">

These lines aren't meeting the nodes :sadge:, if this is too much of a pain, maybe we remove the line on mobile?

<img width="259" alt="Screenshot 2021-08-21 at 5 52 35 PM" src="https://user-images.githubusercontent.com/39828164/130318158-95837670-1da2-433b-a3b1-402bbbba3c19.png">

These don't all line up:

<img width="250" alt="Screenshot 2021-08-21 at 5 54 07 PM" src="https://user-images.githubusercontent.com/39828164/130318204-13c66eae-ef47-4baf-a301-9765a011f7c5.png">

There's still some horizontal overflow on the event cards:

<img width="837" alt="Screenshot 2021-08-21 at 5 55 16 PM" src="https://user-images.githubusercontent.com/39828164/130318225-b7d65844-7e3d-431d-8f68-c72fad9de08b.png">

Could we remove the left padding on the attendees stat so these all line up?

<img width="176" alt="Screenshot 2021-08-21 at 5 55 49 PM" src="https://user-images.githubusercontent.com/39828164/130318244-c2a64fdf-c8ed-4283-9961-47bb701ab8fe.png">

Could we reduce the gap between the image and the text content here?

<img width="595" alt="Screenshot 2021-08-21 at 5 56 39 PM" src="https://user-images.githubusercontent.com/39828164/130318271-0009a56a-0044-4799-be1f-f14575fbc5a3.png">

Once again, thank you so so much Ella, I can't say it enough

2021-08-21 21:39 UTC, eilla1 commented
Appreciate the thorough review, thanks Sam :D

Along with the other style issues, I also fixed the lines on the timeline to be a fixed height instead of a percentage, so now it should work on all screen heights

2021-08-22 06:05 UTC, sampoder approved these changes
Hoorah! I think this is ready to ship! thank you so much Ella for all of this, this is amazing!

2021-08-22 06:05 UTC, merged